defaults:
  -
    values:
      layout: "default"

permalink: /:categories/:title

# Namespace for custom variables
pm:
  root: "https://www.getpostman.com"
  gs: "https://app.getpostman.com"
  blog: "http://blog.getpostman.com"
  support_center: "https://support.getpostman.com/hc"
  help_email: "help@getpostman.com"
  enterprise_email: "enterprise@getpostman.com"
  security_email: "security@getpostman.com"

# Website metadata
meta:
  tracker: "GTM-M42M5N"

# HTTP-REFRESH meta tag for v1 redirects
gems:
  - jekyll-redirect-from
  - algoliasearch-jekyll

exclude: [vendor]

# Search
algolia:
  application_id: 'SDZ6C0ROMM'
  index_name: 'blog'
  read_only_api_key: 'e83c353e0b538a05ad8ea1d70c32b0dd'
  excluded_files:
    - 404.html
    - index.html
    - _site/account.html
    - _site/apimatic.html
    - _site/bigpanda.html
    - _site/blog_mentions.html
    - _site/buying_cloud.html
    - _site/capture.html
    - _site/capture_native.html
    - _site/chaining_requests.html
    - _site/checking_payload_responses.html
    - _site/cloud.html
    - _site/cloud_api.html
    - _site/cloud_team_setup.html
    - _site/code_snippets.html
    - _site/collections.html
    - _site/consuming_api_documentation.html
    - _site/creating_curl.html
    - _site/creating_documentation.html
    - _site/datadog.html
    - _site/dropbox_integration.html
    - _site/env_run_button.html
    - _site/environments.html
    - _site/errors.html
    - _site/faq.html
    - _site/github_integration.html
    - _site/gitlab_integration.html
    - _site/handling_redirects.html
    - _site/helpers.html
    - _site/integrating_with_jenkins.html
    - _site/history.html
    - _site/ignoring_ssl.html
    - _site/importing_curl.html
    - _site/importing_folders.html
    - _site/importing_swagger.html
    - _site/index.html
    - _site/install_native.html
    - _site/integrating_with_jenkins.html
    - _site/integrations.html
    - _site/interceptor_cookies.html
    - _site/introduction.html
    - _site/jetpacks_intro.html
    - _site/keen_integration.html
    - _site/keyvalue_editor.html
    - _site/launch.html
    - _site/migration.html
    - _site/migration_new.html
    - _site/monitors.html
    - _site/multiple_instances.html
    - _site/newman_in_docker.html
    - _site/newman_intro.html
    - _site/pagerduty_integration.html
    - _site/pre_request_scripts.html
    - _site/pricing-policy.html
    - _site/reference.html
    - _site/requests.html
    - _site/responses.html
    - _site/run_button.html
    - _site/run_button_api.html
    - _site/run_button_ux.html
    - _site/run_file_post_requests.html
    - _site/run_partner_prog.html
    - _site/run_security.html
    - _site/running_collections.html
    - _site/sandbox.html
    - _site/schedule_cloud_runs.html
    - _site/search.html
    - _site/security.html
    - _site/self_signed_certs.html
    - _site/settings.html
    - _site/sharing.html
    - _site/slack_integration.html
    - _site/soap_requests.html
    - _site/sync_gettingstarted.html
    - _site/sync_overview.html
    - _site/tabs.html
    - _site/test_multi-environments.html
    - _site/testing_examples.html
    - _site/text_editor.html
    - _site/update_run_button.html
    - _site/updating.html
    - _site/validating_json_collections.html
    - _site/victorops.html
    - _site/videos.html
    - _site/why_native.html
    - _site/workflows.html
    - _site/working_with_client_certificates.html
    - _site/working_with_cookies.html
    - _site/writing_tests.html
    - _posts/07_getting_started/
    - _posts/08_sending_and_viewing_responses/
    - _posts/09_managing_collections/
    - _posts/10_variables_and_environments/
    - _posts/11_postman_for_teams/
    - _posts/12_api_testing_and_collection_runner/
    - _posts/13_postman_for_public_apis/
    - _posts/14_settings/
    - _posts/15_billing_and_payment/
    - _posts/16_account_profile/
    - _posts/17_miscellaneous/
    - _posts/18_postman_pro_integrations/
    - _posts/01_postman/2017-05-04-mock_servers.md
    - _posts/03_enterprise/2017-05-04-apply_for_beta_access.md

