defaults:
  -
    values:
      layout: "default"

permalink: /:categories/:title

# Namespace for custom variables
pm:
  root: "https://www.getpostman.com"
  gs: "https://app.getpostman.com"
  blog: "http://blog.getpostman.com"
  support_center: "https://support.getpostman.com/hc"
  help_email: "help@getpostman.com"
  enterprise_email: "enterprise@getpostman.com"
  security_email: "security@getpostman.com"

# Website metadata
meta:
  tracker: "GTM-M42M5N"

# HTTP-REFRESH meta tag for v1 redirects
gems:
  - jekyll-redirect-from

exclude: [vendor]