
name: manually re-running actions

on: repository_dispatch

jobs:
  manual_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - name: lint all markdownfiles
      env:
        PM_TECH_RT: ${{secrets.PM_TECH_RT}}
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        npm install
        node_modules/.bin/markdownlint ./ --ignore node_modules
    - name: check for image url
      run: |
        if grep -lri 's3.amazonaws.com/postman-static-getpostman-com' ./src/pages/docs ;
        then echo "Invalid s3 references found. Please use format 'https://assets.postman.com/postman-docs/[filename-in-s3]'";
          exit 1;
        else echo "no s3 references found";
        fi
    - name: running unit tests
      env:
        PM_TECH_RT: ${{secrets.PM_TECH_RT}}
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        npm install
        npm run clean
        npm run test:update
