name: Prod Deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - name: set AWS, BFF, NewRelic and Algolia Keys to environment
      env:
        GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
        GATSBY_ALGOLIA_SEARCH_KEY: ${{secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
        ALGOLIA_ADMIN_KEY: ${{secrets.ALGOLIA_ADMIN_KEY}}
        AWS_ACCESS_KEY_ID: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY}}
        DIST_ID: ${{secrets.PROD_DIST_ID}}
        MUNCHKIN_ID: ${{ secrets.MUNCHKIN_ID}}
        BFF_BLOG_URL: ${{ secrets.BFF_BLOG_URL }}
        BFF_EVENTS_URL: ${{ secrets.BFF_EVENTS_URL }}
        BFF_FOOTER_URL: ${{ secrets.BFF_FOOTER_URL }}
        BFF_NAVBAR_URL: ${{ secrets.BFF_NAVBAR_URL }}
        BFF_PING_WEBHOOK_URL: ${{ secrets.BFF_PING_WEBHOOK_URL }}
        RELIC_ACCOUNT_ID: ${{ secrets.RELIC_ACCOUNT_ID }}
        RELIC_TRUST_KEY: ${{ secrets.RELIC_TRUST_KEY }}
        RELIC_LICENSE_KEY: ${{ secrets.RELIC_LICENSE_KEY }}
        RELIC_PRODUCTION_AGENT_ID: ${{ secrets.RELIC_PRODUCTION_AGENT_ID }}
        RELIC_PRODUCTION_APPLICATION_ID: ${{ secrets.RELIC_PRODUCTION_APPLICATION_ID }}
        PM_TECH_RT: ${{secrets.PM_TECH_RT}}
        SITE_URL: ${{secrets.SITE_URL_PROD}}

      run: |
        npm config set //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}
        npm install
        npm run clean
        npm run build:prod && node_modules/s3-deploy/bin/s3-deploy './public/**' --cwd './public/' --bucket postman-learning-center-prod --deleteRemoved --distId $DIST_ID --invalidate '/*'
